Fixed MariaDB installation.
Error: [ERROR] mariadbd: Can't open shared library '/usr/lib/mysql/plugin/provider_bzip2.so'.
(cherry picked from commit 2bdfade86577b71e0f2da3bd34aa9fb6da8f191c)